adding deployments

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -113,9 +113,17 @@ jobs:
         export PATH=\$PATH:/usr/local/go/bin  # Ensure Go is in PATH
         go version  # Verify Go version
         go build -o main
-        tmux kill-session -t ecoop-dev &> /dev/null || true
-        tmux new-session -d -s ecoop-dev
-        tmux send-keys -t ecoop-dev './main' C-m
+
+
+        tmux kill-session -t ecoop-development || true
+        tmux new-session -d -s ecoop-development
+        tmux send-keys -t ecoop-development 'git pull' C-m
+        tmux send-keys -t ecoop-development 'if [ $? -ne 0 ]; then echo "Git pull failed"; exit 1; fi' C-m
+
+        # Run start script
+        tmux send-keys -t ecoop-development './main' C-m
+        tmux send-keys -t ecoop-development 'if [ $? -ne 0 ]; then echo "Start script failed"; exit 1; fi' C-m
+
 
         echo "Development deployment completed!"
         EOF
